/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Redirect to AniList authorization URL */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Redirect to AniList authorization URL successful. */
                308: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Request must be made through the host device. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                500: components["responses"]["InternalServerError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Exchange authorization code for access & refresh token */
        get: {
            parameters: {
                query: {
                    /** @description Authorization Code */
                    code: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Exchange successful. */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                400: components["responses"]["BadRequest"];
                /** @description Request must be made through the host device. */
                401: components["responses"]["Unauthorized"];
                500: components["responses"]["InternalServerError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/media": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get list of currently watching media */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List successfully retrieved. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["MediaSummary"][];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                500: components["responses"]["InternalServerError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/media/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        /** Get media details and episodes. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Media details successfully retrieved */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["Media"];
                        };
                    };
                };
                404: components["responses"]["NotFound"];
                500: components["responses"]["InternalServerError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/media/{id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        /** Get AniList media status details. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Media status successfully retrieved */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["MediaStatusDetails"];
                        };
                    };
                };
                400: components["responses"]["BadRequest"];
                404: components["responses"]["NotFound"];
                500: components["responses"]["InternalServerError"];
            };
        };
        /** Update AniList media status and progress. */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["MediaStatusDetails"];
                };
            };
            responses: {
                /** @description Updated media status details. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["MediaStatusDetails"];
                        };
                    };
                };
                400: components["responses"]["BadRequest"];
                404: components["responses"]["NotFound"];
                500: components["responses"]["InternalServerError"];
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/episodes/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** Get episode details */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Episode details retrieved successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["Episode"];
                        };
                    };
                };
                404: components["responses"]["NotFound"];
                500: components["responses"]["InternalServerError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/episodes/queue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current queue and progress */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Queue items successfully retrieved */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["QueueItem"][];
                        };
                    };
                };
                500: components["responses"]["InternalServerError"];
            };
        };
        put?: never;
        /** Enqueues a list of episodes to be processed for streaming. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        media_id: number;
                        items: {
                            /** @description Absolute path of the video file in the host of the server. */
                            path: string;
                            /**
                             * Format: double
                             * @description Episode number, it has to be double due to the possibility of extra episodes.
                             */
                            number?: number;
                        }[];
                    };
                };
            };
            responses: {
                /** @description Episode(s) successfully enqueued. */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                400: components["responses"]["BadRequest"];
                404: components["responses"]["NotFound"];
                500: components["responses"]["InternalServerError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            message: string;
        };
        /** @enum {string} */
        MediaStatus: "PENDING" | "REPEATING" | "COMPLETED" | "DROPPED" | "PAUSED" | "PLANNED";
        MediaSummary: {
            id: number;
            banner: string | null;
            cover: string | null;
            title: string;
            progress: number | null;
            /** @description Total number of episodes */
            total: number | null;
            status: components["schemas"]["MediaStatus"] | null;
        };
        MediaStatusDetails: {
            status: components["schemas"]["MediaStatus"];
            score: number;
            progress: number;
            start_date: null | string;
            finish_date: null | string;
            rewatch_count: number;
            private: boolean;
            note: string;
        };
        EpisodeSummary: {
            /** Format: nanoID */
            id: string;
            title: string | null;
            /** @description Duration of the episode in seconds. */
            duration: number | null;
            /** Format: double */
            number: number;
            thumbnail: string | null;
        };
        Media: {
            id: number;
            banner: string | null;
            cover: null | {
                thumbnail: string;
                original: string;
            };
            title: string;
            progress: number | null;
            /** @description Total number of episodes */
            total: number | null;
            status: components["schemas"]["MediaStatus"] | null;
            episodes?: components["schemas"]["EpisodeSummary"][];
            description?: string | null;
            genres?: string[];
        };
        EpisodeChapter: {
            /** @description Start timestamp of the chapter in milliseconds. */
            start: number;
            name: string;
        };
        /** @enum {string} */
        ProcessingStatus: "QUEUED" | "PROCESSING" | "READY";
        Episode: {
            /** Format: nanoID */
            id: string;
            title: string | null;
            /** @description Duration of the episode in seconds. */
            duration: number;
            /** Format: double */
            number: number;
            thumbnail: string | null;
            media: components["schemas"]["MediaSummary"];
            chapters: components["schemas"]["EpisodeChapter"][];
            /** @description HLS Playlist url (should include domain as well, Local IP address specifically) */
            url: string;
        };
        /** @enum {string} */
        ProcessingStep: "IN_QUEUE" | "PROCESSING_1080P" | "PROCESSING_720P" | "PROCESSING_AUDIO" | "PROCESSING_SUBTITLES" | "PACKAGING" | "DONE";
        QueueItem: {
            /** Format: nanoID */
            id: string;
            step: components["schemas"]["ProcessingStep"];
            /** @description A null indicates the current step doesn't have a progress. */
            progress: number | null;
            media: components["schemas"]["MediaSummary"];
            /** @description The number of the episode being processed */
            number: number;
        };
    };
    responses: {
        /** @description Bad request */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Unauthorized */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Resource not found. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Internal Server Error occurred (500) */
        InternalServerError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
